const albums = [
    {
        '_id': '1',
        'name': 'Crypt of The Necrodancer',
        'image': '/images/cryptofthenecrodancer.jpg',
        'year': 2012,
        'songs': ['First, Second, Third'],
        'category': 'pop',
        'price': 15.99,
        'countInStock': 0,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Dawnmetropolis',
        'image': '/images/dawnmetropolis.jpg',
        'year': 2012,
        'songs': ['First, Second, Third'],
        'category': 'pop',
        'price': 15.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '3',
        'name': 'Metroid Zero Missions',
        'image': '/images/metroidzeromissions.jpg',
        'year': 2012,
        'songs': ['First, Second, Third'],
        'category': 'pop',
        'price': 15.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Sonic Adventure 2',
        'image': '/images/sonicadventure2.jpg',
        'year': 2012,
        'songs': ['First, Second, Third'],
        'category': 'pop',
        'price': 15.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Zelda And Chill',
        'image': '/images/zeldaandchill.jpg',
        'year': 2012,
        'songs': ['First, Second, Third'],
        'category': 'pop',
        'price': 15.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
]

export default albums